name: FluxCraft
version: '1.0.0'
main: io.eol.fluxcraft.FluxCraft
api-version: '1.21'
authors: [Coreflux, jforge]
description: Streams Minecraft events to an MQTT broker
website: https://eol.io
commands:
  mqtt:
    description: FluxCraft commands
    usage: /<command> [reload|status|test]
    permission: mqtt.admin
permissions:
  mqtt.admin:
    description: Allows access to MQTT admin commands
    default: op
